# My config

# Change the default prompt format
add_newline = true
command_timeout = 1000
format = """\
[â•­â•´](238)$os$username$hostname$time$directory\
$all[â•°â”€](238)$character"""

[character]
success_symbol = '[ï€Œ ](bold green)'
error_symbol = '[âœ— ](bold red)'

# ---

[os]
format = '[$symbol](bold white) '   
disabled = false

[os.symbols]
Alpine = 'ïŒ€ '
Amazon = 'ï‰° '
Android = 'ï…» '
Arch = 'ïŒƒ '
Artix = 'ïŒŸ '
CentOS = 'ïŒ„ '
Debian = 'ïŒ† '
EndeavourOS = 'ï†— '
Fedora = 'ïŒŠ '
FreeBSD = 'ïŒŒ '
Garuda = 'ó°›“ '
Gentoo = 'ïŒ '
Linux = 'ïŒš '
Mabox = 'î¬© '
Macos = 'ïŒ‚ '
Manjaro = 'ïŒ’ '
Mint = 'ïŒ '
NixOS = 'ïŒ“ '
OpenBSD = 'ó°ˆº '
openSUSE = 'ïŒ” '
OracleLinux = 'ó°Œ· '
Pop = 'ïŒª '
Raspbian = 'ïŒ• '
Redhat = 'ïŒ– '
SUSE = 'ïŒ” '
Ubuntu = 'ïŒ› '
Unknown = 'ïˆ­ '
Windows = 'ó°² '

[time]
disabled = false
format = 'ï€— [$time]($style) '
time_format = '%R'

# ---

# Shows current directory
[directory]
style = 'bold green'
truncation_length = 1
truncation_symbol = 'â€¦/'
home_symbol = 'ó°‹œ ~'
read_only_style = 'bold red'
read_only = ' ï€£ '
format = 'at [$path]($style)[$read_only]($read_only_style) '

# Shows the username
[username]
style_user = '#0089f5'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_symbol = 'î¬ '
ssh_only = false
format = 'on [$hostname](bold yellow) '
disabled = false

# Shows current git branch
[git_branch]
symbol = 'ï˜ '
format = 'via [$symbol$branch]($style)'
# truncation_length = 4
truncation_symbol = 'â€¦/'
style = 'bold cyan'

# Shows current git status
[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bold cyan'
conflicted = ' ğŸ³'
up_to_date = ' '
untracked = ' ï”© '
ahead = ' â‡¡${count}'
diverged = ' â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = ' â‡£${count}'
stashed = ' ó°— '
modified = ' ï„ '
staged = ' [++\($count\)](cyan)'
renamed = ' è¥ '
deleted = ' ï€” '

# Other symbols/icons
[aws]
symbol = 'îŒ½  '
format = 'via [$symbol$version](bold #FF9900) '

[c]
symbol = 'î˜ '
format = 'via [$symbol$version](bold #659AD2) '

[dart]
symbol = 'î˜ '
format = 'via [$symbol$version](bold #0075BA) '

[docker_context]
symbol = 'ïŒˆ '
format = 'via [$symbol$version](bold #1D63ED) '

[golang]
symbol = 'î˜§ '
format = 'via [$symbol$version](bold #29BEB0) '

[java]
symbol = 'î‰– '
format = 'via [$symbol$version](bold #F8981D) '

[kubernetes]
symbol = 'â˜¸ '
format = 'via [$symbol$context\($namespace\)](bold #326DE6) '
disabled = false

[lua]
symbol = 'î˜  '
format = 'via [$symbol$version](bold white) '

[memory_usage]
symbol = 'ó°› '

[nodejs]
symbol = 'îœ˜ '
format = 'via [$symbol$version](bold #3C873A) '

[package]
symbol = 'ó°— '

[python]
symbol = 'îˆµ '
format = 'via [$symbol$version](bold #FFD343) '

[ruby]
symbol = 'î‘ '
format = 'via [$symbol$version](bold #841B2D) '

[rust]
symbol = 'î¨ '
format = 'via [$symbol$version](bold #CE412B) '

[scala]
symbol = 'îœ· '
format = 'via [$symbol$version](bold #DE3423) '
