# My config

# Change the default prompt format
add_newline = true
command_timeout = 1000
format = """\
[â•­â•´](238)$os\
$all[â•°â”€](238)$character"""

[character]
success_symbol = "[ï€Œ ](bold green)"
error_symbol = "[âœ— ](bold red)"

# ---

[os]
format = '[$symbol](bold white) '   
disabled = false

[os.symbols]
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mint = "ïŒ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ó°² "

# ---

# Shows current directory
[directory]
style = 'bold green'
truncation_length = 1
truncation_symbol = 'â€¦/'
home_symbol = 'ó°‹œ ~'
read_only_style = 'bold red'
read_only = ' ï€£ '
format = 'at [$path]($style)[$read_only]($read_only_style) '

# Shows the username
[username]
style_user = '#0089f5'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_symbol = "î¬ "
ssh_only = false
format = 'on [$hostname](bold yellow) '
disabled = false

# Shows current git branch
[git_branch]
symbol = "ï˜ "
format = 'via [$symbol$branch]($style)'
# truncation_length = 4
truncation_symbol = 'â€¦/'
style = 'bold cyan'

# Shows current git status
[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bold cyan'
conflicted = ' ğŸ³'
up_to_date = ' '
untracked = ' ï”© '
ahead = ' â‡¡${count}'
diverged = ' â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = ' â‡£${count}'
stashed = ' ó°— '
modified = ' ï„ '
staged = ' [++\($count\)](cyan)'
renamed = ' è¥ '
deleted = ' ï€” '

# Other symbols/icons
[aws]
symbol = "îŒ½  "
format = "[via $symbol$version] "

[c]
symbol = "î˜ "
format = "[via $symbol$version] "

[conda]
symbol = "ï„Œ "
format = "[via $symbol$version] "

[dart]
symbol = "î˜ "
format = "[via $symbol$version] "

[docker_context]
symbol = "ïŒˆ "
format = "[via $symbol$version] "

[golang]
symbol = "î˜§ "
format = "[via $symbol$version] "

[haskell]
symbol = "î· "
format = "[via $symbol$version] "

[java]
symbol = "î‰– "
format = "[$symbol$version] "

[kubernetes]
symbol = "â˜¸ "
format = 'via [$symbol$context\($namespace\)](bold purple) '
disabled = false

[lua]
symbol = "î˜  "
format = "[via $symbol$version] "

[memory_usage]
symbol = "ó°› "

[nodejs]
symbol = "îœ˜ "
format = "[via $symbol$version] "

[package]
symbol = "ó°— "

[python]
symbol = "îˆµ "
format = "[via $symbol$version]"

[ruby]
symbol = "î‘ "
format = "[via $symbol$version] "

[rust]
symbol = "î¨ "
format = "[via $symbol$version] "

[scala]
symbol = "îœ· "
format = "[via $symbol$version] "
